# Perfilamiento de memoria

In [1]:
from memory_profiler import memory_usage
import time

In [2]:
!pip install --quiet "git+https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-caroacostatovany.git#egg=mex&subdirectory=src"

In [3]:
#!pip uninstall mex -y

In [4]:
import copy
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import os
import pprint
from scipy.optimize import linprog
from pytest import approx

from mex.simplex.simplex_networks import create_matrix, pivots_col, pivots_row, find_negative_col, find_negative_row, find_pivot_col, find_pivot_row, pivot
from mex.simplex.problem_definition import add_cons, constrain, add_obj, obj, maxz, minz

## Objetivo

In [5]:
c_max_obj_1 = [-3, -5]
A_max_obj_1 = [[1, 0], [0, 2], [3, 2]]
b_max_obj_1 = [4, 12, 18]

In [6]:
max_obj_1 = -1*linprog(c_max_obj_1, A_ub=A_max_obj_1, b_ub=b_max_obj_1).fun

In [7]:
coeff_obj_1 = linprog(c_max_obj_1, A_ub=A_max_obj_1, b_ub=b_max_obj_1).x

## Aproximación

In [8]:
n_var_approx_1 = 2
n_cons_approx_1 = 3

In [9]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (create_matrix, (n_var_approx_1,n_cons_approx_1))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 106.1015625
max mem 106.296875
used mem 0.1953125
fun output [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [10]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (constrain, (matrix_max_approx_1, '1,0,L,4', True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 106.53515625
max mem 106.5859375
used mem 0.05078125
fun output [[1. 0. 1. 0. 0. 0. 4.]
 [1. 0. 0. 1. 0. 0. 4.]
 [1. 0. 0. 0. 1. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
constrain(matrix_max_approx_1,'1,0,L,4')
constrain(matrix_max_approx_1,'0,2,L,12')
constrain(matrix_max_approx_1,'3,2,L,18')
t = (constrain, (matrix_max_approx_1, '3,2,L,18', True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 106.64453125
max mem 106.66796875
used mem 0.0234375
fun output [[ 1.  0.  1.  0.  0.  0.  4.]
 [ 0.  2.  0.  1.  0.  0. 12.]
 [ 3.  2.  0.  0.  1.  0. 18.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [12]:
t = (obj, (matrix_max_approx_1, '3,5,0'))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 106.671875
max mem 106.671875
used mem 0.0
fun output None


In [13]:
t = (maxz, (matrix_max_approx_1,True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 106.671875
max mem 106.6875
used mem 0.015625
fun output {'x1': 2.0, 'x2': 6.0, 'max': 36.0}


In [14]:
def profiling_memory_example(matrix, aux=True):
    """
    Realizar todo el proceso del problema a resolver de optimización con el método Simplex
    """
    constrain(matrix,'1,0,L,4')
    constrain(matrix,'0,2,L,12')
    constrain(matrix,'3,2,L,18')
    obj(matrix,'3,5,0')
    problem_approx_1 = maxz(matrix)
    max_approx_1 = problem_approx_1['max']
    problem_approx_1.pop('max')
    coeff_approx_1 = np.array(list(problem_approx_1.values()))
    
    return max_approx_1, coeff_approx_1

In [15]:
# Todo junto
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (profiling_memory_example, (matrix_max_approx_1,True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 106.7421875
max mem 106.7421875
used mem 0.0
fun output (36.0, array([2., 6.]))


In [16]:
# Guardar variables para comprobación
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
constrain(matrix_max_approx_1,'1,0,L,4')
constrain(matrix_max_approx_1,'0,2,L,12')
constrain(matrix_max_approx_1,'3,2,L,18')
obj(matrix_max_approx_1,'3,5,0')
problem_approx_1 = maxz(matrix_max_approx_1)
max_approx_1 = problem_approx_1['max']
problem_approx_1.pop('max')
coeff_approx_1 = np.array(list(problem_approx_1.values()))

## Comprobación

In [17]:
assert max_obj_1 == approx(max_approx_1), "El valor aproximado es incorrecto"
assert coeff_obj_1 == approx(coeff_approx_1), "El valor de los coeficientes aproximados es incorrecto"

print("El valor objetivo obtenido con scipy es: ", max_obj_1)
print("El valor aproximado obtenido con mex es: ", max_approx_1)
print("Los coeficientes objetivos obtenidos con scipy son: ", coeff_obj_1)
print("Los coeficientes aproximados obtenidos con mex son: ", coeff_approx_1)

El valor objetivo obtenido con scipy es:  35.99999997843401
El valor aproximado obtenido con mex es:  36.0
Los coeficientes objetivos obtenidos con scipy son:  [2. 6.]
Los coeficientes aproximados obtenidos con mex son:  [2. 6.]


# Con `%memit`

In [18]:
%load_ext memory_profiler

In [19]:
%memit

peak memory: 106.82 MiB, increment: 0.00 MiB


In [20]:
%memit -c profiling_memory_example(create_matrix(n_var_approx_1,n_cons_approx_1), True)

peak memory: 188.91 MiB, increment: 82.10 MiB


# Con `%mprun`

In [21]:
os.chdir('/home/ubuntu/practica-2-segunda-parte-caroacostatovany')

In [22]:
from src.profiling.memoria.maxz_memory_profiler import profiling_memory_example

In [23]:
matrix_max_approx_1 = create_matrix(n_var_approx_1, n_cons_approx_1)

In [24]:
%mprun -f profiling_memory_example profiling_memory_example(matrix_max_approx_1)

Filename: /home/ubuntu/practica-2-segunda-parte-caroacostatovany/src/profiling/memoria/maxz_memory_profiler.py

Line #    Mem usage    Increment  Occurences   Line Contents
     9    107.4 MiB    107.4 MiB           1   @profile
    10                                         def profiling_memory_example(matrix, aux=True):
    11                                             """
    12                                             Problema a resolver de optimización con el método Simplex
    13                                             """
    14    107.4 MiB      0.0 MiB           1       constrain(matrix, '1,0,L,4')
    15    107.4 MiB      0.0 MiB           1       constrain(matrix, '0,2,L,12')
    16    107.4 MiB      0.0 MiB           1       constrain(matrix, '3,2,L,18')
    17    107.4 MiB      0.0 MiB           1       obj(matrix, '3,5,0')
    18    107.4 MiB      0.0 MiB           1       problem_approx_1 = maxz(matrix)
    19    107.4 MiB      0.0 MiB           1       max_appro

Filename: /home/ubuntu/.local/lib/python3.8/site-packages/memory_profiler.py

Line #    Mem usage    Increment  Occurences   Line Contents
  1140    107.4 MiB    107.4 MiB           1               def wrapper(*args, **kwargs):
  1141    107.4 MiB      0.0 MiB           1                   prof = get_prof()
  1142    107.4 MiB      0.0 MiB           1                   val = prof(func)(*args, **kwargs)
  1143    107.4 MiB      0.0 MiB           1                   show_results_bound(prof)
  1144    107.4 MiB      0.0 MiB           1                   return val

Problema de mediana escala

In [25]:
from src.profiling.memoria.maxz_memory_profiler_medium_size import profiling_memory_example

In [26]:
matrix_max_approx_1 = create_matrix(20, 30)

In [27]:
%mprun -f profiling_memory_example profiling_memory_example(matrix_max_approx_1)

Filename: /home/ubuntu/practica-2-segunda-parte-caroacostatovany/src/profiling/memoria/maxz_memory_profiler_medium_size.py

Line #    Mem usage    Increment  Occurences   Line Contents
     9    107.8 MiB    107.8 MiB           1   @profile
    10                                         def profiling_memory_example(matrix, aux=True):
    11                                             """
    12                                             Problema a resolver de optimización con el método Simplex
    13                                             """
    14                                             
    15                                             #Restricciones 1-5:
    16    107.8 MiB      0.0 MiB           1       matrix=constrain(matrix,'90.09,50.61,45.03,16.83,26.92,36.29,51.61,2.450,25.15,30.22,81.78,2.444,34.71,57.17,41.14,92.00,69.17,26.77,38.44,25.35,L,79.72',True)
    17    107.8 MiB      0.0 MiB           1       matrix=constrain(matrix,'69.62,6.235,18.95,4.843,12.34,82.56

Filename: /home/ubuntu/.local/lib/python3.8/site-packages/memory_profiler.py

Line #    Mem usage    Increment  Occurences   Line Contents
  1140    107.8 MiB    107.8 MiB           1               def wrapper(*args, **kwargs):
  1141    107.8 MiB      0.0 MiB           1                   prof = get_prof()
  1142    107.8 MiB      0.0 MiB           1                   val = prof(func)(*args, **kwargs)
  1143    107.8 MiB      0.0 MiB           1                   show_results_bound(prof)
  1144    107.8 MiB      0.0 MiB           1                   return val

# Con `heapy`

Ejercicio a pequeña escala

In [28]:
%run -i src/profiling/memoria/maxz_memory_profile_heapy.py

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


Partition of a set of 6 objects. Total size = 1080 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1  17      408  38       408  38 types.FrameType
     1      1  17      344  32       752  70 numpy.ndarray
     2      1  17      232  21       984  91 dict (no owner)
     3      3  50       96   9      1080 100 numpy.float64


Ejercicio a mediana escala

In [29]:
%run -i src/profiling/memoria/maxz_memory_profile_heapy_medium_size.py

Partition of a set of 13 objects. Total size = 14576 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1   8    13016  89     13016  89 numpy.ndarray
     1      1   8      640   4     13656  94 dict (no owner)
     2      1   8      408   3     14064  96 types.FrameType
     3      1   8      136   1     14200  97 _io.StringIO
     4      2  15      112   1     14312  98 list
     5      3  23       96   1     14408  99 numpy.float64
     6      1   8       72   0     14480  99 builtins.weakref
     7      2  15       56   0     14536 100 int
     8      1   8       40   0     14576 100 _thread.lock


# Para minz

In [30]:
%run -i src/profiling/memoria/minz_memory_profile_heapy.py

Partition of a set of 10 objects. Total size = 1264 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1  10      408  32       408  32 types.FrameType
     1      1  10      264  21       672  53 numpy.ndarray
     2      1  10      232  18       904  72 dict (no owner)
     3      1  10      136  11      1040  82 _io.StringIO
     4      3  30       96   8      1136  90 numpy.float64
     5      1  10       72   6      1208  96 builtins.weakref
     6      2  20       56   4      1264 100 int


# Para net

In [31]:
%run -i src/profiling/memoria/net_memory_profile_heapy.py

Partition of a set of 13 objects. Total size = 2368 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1   8     1144  48      1144  48 numpy.ndarray
     1      1   8      408  17      1552  66 types.FrameType
     2      1   8      360  15      1912  81 dict (no owner)
     3      6  46      192   8      2104  89 numpy.float64
     4      1   8      136   6      2240  95 _io.StringIO
     5      1   8       72   3      2312  98 builtins.weakref
     6      2  15       56   2      2368 100 int
