# Perfilamiento de memoria

In [1]:
from memory_profiler import memory_usage
import time

In [2]:
!pip install --quiet "git+https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-caroacostatovany.git#egg=mex&subdirectory=src"

In [3]:
#!pip uninstall mex -y

In [4]:
import copy
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import os
import pprint
from scipy.optimize import linprog
from pytest import approx

from mex.simplex.simplex_networks import create_matrix, pivots_col, pivots_row, find_negative_col, find_negative_row, find_pivot_col, find_pivot_row, pivot
from mex.simplex.problem_definition import add_cons, constrain, add_obj, obj, maxz, minz

## Objetivo

In [5]:
c_max_obj_1 = [-3, -5]
A_max_obj_1 = [[1, 0], [0, 2], [3, 2]]
b_max_obj_1 = [4, 12, 18]

In [6]:
max_obj_1 = -1*linprog(c_max_obj_1, A_ub=A_max_obj_1, b_ub=b_max_obj_1).fun

In [7]:
coeff_obj_1 = linprog(c_max_obj_1, A_ub=A_max_obj_1, b_ub=b_max_obj_1).x

## Aproximación

In [8]:
n_var_approx_1 = 2
n_cons_approx_1 = 3

In [9]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (create_matrix, (n_var_approx_1,n_cons_approx_1))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.48046875
max mem 94.69140625
used mem 0.2109375
fun output [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [10]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (constrain, (matrix_max_approx_1, '1,0,L,4', True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.75390625
max mem 94.76171875
used mem 0.0078125
fun output [[1. 0. 1. 0. 0. 0. 4.]
 [1. 0. 0. 1. 0. 0. 4.]
 [1. 0. 0. 0. 1. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
constrain(matrix_max_approx_1,'1,0,L,4')
constrain(matrix_max_approx_1,'0,2,L,12')
constrain(matrix_max_approx_1,'3,2,L,18')
t = (constrain, (matrix_max_approx_1, '3,2,L,18', True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.80859375
max mem 94.8125
used mem 0.00390625
fun output [[ 1.  0.  1.  0.  0.  0.  4.]
 [ 0.  2.  0.  1.  0.  0. 12.]
 [ 3.  2.  0.  0.  1.  0. 18.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [12]:
t = (obj, (matrix_max_approx_1, '3,5,0'))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.82421875
max mem 94.82421875
used mem 0.0
fun output None


In [13]:
t = (maxz, (matrix_max_approx_1,True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.8359375
max mem 94.83984375
used mem 0.00390625
fun output {'x1': 2.0, 'x2': 6.0, 'max': 36.0}


In [14]:
def profiling_memory_example(matrix, aux=True):
    """
    Realizar todo el proceso del problema a resolver de optimización con el método Simplex
    """
    constrain(matrix,'1,0,L,4')
    constrain(matrix,'0,2,L,12')
    constrain(matrix,'3,2,L,18')
    obj(matrix,'3,5,0')
    problem_approx_1 = maxz(matrix)
    max_approx_1 = problem_approx_1['max']
    problem_approx_1.pop('max')
    coeff_approx_1 = np.array(list(problem_approx_1.values()))
    
    return max_approx_1, coeff_approx_1

In [15]:
# Todo junto
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (profiling_memory_example, (matrix_max_approx_1,True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.89453125
max mem 94.90625
used mem 0.01171875
fun output (36.0, array([2., 6.]))


In [16]:
# Guardar variables para comprobación
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
constrain(matrix_max_approx_1,'1,0,L,4')
constrain(matrix_max_approx_1,'0,2,L,12')
constrain(matrix_max_approx_1,'3,2,L,18')
obj(matrix_max_approx_1,'3,5,0')
problem_approx_1 = maxz(matrix_max_approx_1)
max_approx_1 = problem_approx_1['max']
problem_approx_1.pop('max')
coeff_approx_1 = np.array(list(problem_approx_1.values()))

## Comprobación

In [17]:
assert max_obj_1 == approx(max_approx_1), "El valor aproximado es incorrecto"
assert coeff_obj_1 == approx(coeff_approx_1), "El valor de los coeficientes aproximados es incorrecto"

print("El valor objetivo obtenido con scipy es: ", max_obj_1)
print("El valor aproximado obtenido con mex es: ", max_approx_1)
print("Los coeficientes objetivos obtenidos con scipy son: ", coeff_obj_1)
print("Los coeficientes aproximados obtenidos con mex son: ", coeff_approx_1)

El valor objetivo obtenido con scipy es:  35.999999978433735
El valor aproximado obtenido con mex es:  36.0
Los coeficientes objetivos obtenidos con scipy son:  [2. 6.]
Los coeficientes aproximados obtenidos con mex son:  [2. 6.]


# Con `%memit`

In [18]:
%load_ext memory_profiler

In [19]:
%memit

peak memory: 94.68 MiB, increment: -0.31 MiB


In [20]:
%memit -c profiling_memory_example(create_matrix(n_var_approx_1,n_cons_approx_1), True)

peak memory: 100.21 MiB, increment: 5.53 MiB


# Con `%mprun`

In [33]:
from src.profiling.memoria.maxz_memory_profiler import profiling_memory_example

In [34]:
matrix_max_approx_1 = create_matrix(n_var_approx_1, n_cons_approx_1)

In [35]:
%mprun -f profiling_memory_example profiling_memory_example(matrix_max_approx_1)

Filename: /Users/eduardomorenoortiz/Desktop/MaestriaCD/Semestres/Semestre2/optimizacion_avanzada/practicas/practica_2/practica-2-segunda-parte-caroacostatovany/src/profiling/memoria/maxz_memory_profiler.py

Line #    Mem usage    Increment  Occurences   Line Contents
     9    115.6 MiB    115.6 MiB           1   @profile
    10                                         def profiling_memory_example(matrix, aux=True):
    11                                             """
    12                                             Problema a resolver de optimización con el método Simplex
    13                                             """
    14    115.7 MiB      0.0 MiB           1       constrain(matrix, '1,0,L,4')
    15    115.7 MiB      0.0 MiB           1       constrain(matrix, '0,2,L,12')
    16    115.7 MiB      0.0 MiB           1       constrain(matrix, '3,2,L,18')
    17    115.7 MiB      0.0 MiB           1       obj(matrix, '3,5,0')
    18    115.7 MiB      0.0 MiB           1    

Problema de mediana escala

In [36]:
from src.profiling.memoria.maxz_memory_profiler import profiling_memory_example

In [37]:
matrix_max_approx_1 = create_matrix(20, 30)

In [38]:
%mprun -f profiling_memory_example profiling_memory_example(matrix_max_approx_1)

Filename: /Users/eduardomorenoortiz/Desktop/MaestriaCD/Semestres/Semestre2/optimizacion_avanzada/practicas/practica_2/practica-2-segunda-parte-caroacostatovany/src/profiling/memoria/maxz_memory_profiler.py

Line #    Mem usage    Increment  Occurences   Line Contents
     9    115.7 MiB    115.7 MiB           1   @profile
    10                                         def profiling_memory_example(matrix, aux=True):
    11                                             """
    12                                             Problema a resolver de optimización con el método Simplex
    13                                             """
    14    115.7 MiB      0.0 MiB           1       constrain(matrix, '1,0,L,4')
    15    115.7 MiB      0.0 MiB           1       constrain(matrix, '0,2,L,12')
    16    115.7 MiB      0.0 MiB           1       constrain(matrix, '3,2,L,18')
    17    115.7 MiB      0.0 MiB           1       obj(matrix, '3,5,0')
    18    115.7 MiB      0.0 MiB           1    

# Con `heapy`

Ejercicio a pequeña escala

In [24]:
%run -i ../src/profiling/memoria/maxz_memory_profile_heapy.py

Partition of a set of 6 objects. Total size = 1088 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1  17      416  38       416  38 types.FrameType
     1      1  17      336  31       752  69 numpy.ndarray
     2      1  17      240  22       992  91 dict (no owner)
     3      3  50       96   9      1088 100 numpy.float64


Ejercicio a mediana escala

In [41]:
%run -i ../src/profiling/memoria/maxz_memory_profile_heapy_medium_size.py

Partition of a set of 9 objects. Total size = 14312 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1  11    13008  91     13008  91 numpy.ndarray
     1      1  11      648   5     13656  95 dict (no owner)
     2      1  11      416   3     14072  98 types.FrameType
     3      3  33       96   1     14168  99 numpy.float64
     4      1  11       80   1     14248 100 builtins.weakref
     5      2  22       64   0     14312 100 int


# Para minz

In [25]:
%run -i ../src/profiling/memoria/minz_memory_profile_heapy.py

Partition of a set of 10 objects. Total size = 1296 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1  10      416  32       416  32 types.FrameType
     1      1  10      256  20       672  52 numpy.ndarray
     2      1  10      240  19       912  70 dict (no owner)
     3      1  10      144  11      1056  81 _io.StringIO
     4      3  30       96   7      1152  89 numpy.float64
     5      1  10       80   6      1232  95 builtins.weakref
     6      2  20       64   5      1296 100 int


# Para net

In [26]:
%run -i ../src/profiling/memoria/net_memory_profile_heapy.py

Partition of a set of 13 objects. Total size = 2400 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1   8     1136  47      1136  47 numpy.ndarray
     1      1   8      416  17      1552  65 types.FrameType
     2      1   8      368  15      1920  80 dict (no owner)
     3      6  46      192   8      2112  88 numpy.float64
     4      1   8      144   6      2256  94 _io.StringIO
     5      1   8       80   3      2336  97 builtins.weakref
     6      2  15       64   3      2400 100 int
