# Perfilamiento de memoria

In [1]:
from memory_profiler import memory_usage
import time

In [2]:
!pip install --quiet "git+https://github.com/optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-caroacostatovany.git#egg=mex&subdirectory=src"

In [3]:
#!pip uninstall mex -y

In [4]:
import copy
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import os
import pprint
from scipy.optimize import linprog
from pytest import approx

from mex.simplex.simplex_networks import create_matrix, pivots_col, pivots_row, find_negative_col, find_negative_row, find_pivot_col, find_pivot_row, pivot
from mex.simplex.problem_definition import add_cons, constrain, add_obj, obj, maxz, minz

## Objetivo

In [5]:
c_max_obj_1 = [-3, -5]
A_max_obj_1 = [[1, 0], [0, 2], [3, 2]]
b_max_obj_1 = [4, 12, 18]

In [6]:
max_obj_1 = -1*linprog(c_max_obj_1, A_ub=A_max_obj_1, b_ub=b_max_obj_1).fun

In [7]:
coeff_obj_1 = linprog(c_max_obj_1, A_ub=A_max_obj_1, b_ub=b_max_obj_1).x

## Aproximación

In [8]:
n_var_approx_1 = 2
n_cons_approx_1 = 3

In [9]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (create_matrix, (n_var_approx_1,n_cons_approx_1))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.1875
max mem 94.3984375
used mem 0.2109375
fun output [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [10]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (constrain, (matrix_max_approx_1, '1,0,L,4', True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.4765625
max mem 94.4921875
used mem 0.015625
fun output [[1. 0. 1. 0. 0. 0. 4.]
 [1. 0. 0. 1. 0. 0. 4.]
 [1. 0. 0. 0. 1. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [11]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
constrain(matrix_max_approx_1,'1,0,L,4')
constrain(matrix_max_approx_1,'0,2,L,12')
constrain(matrix_max_approx_1,'3,2,L,18')
t = (constrain, (matrix_max_approx_1, '3,2,L,18', True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.51953125
max mem 94.51953125
used mem 0.0
fun output [[ 1.  0.  1.  0.  0.  0.  4.]
 [ 0.  2.  0.  1.  0.  0. 12.]
 [ 3.  2.  0.  0.  1.  0. 18.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [12]:
t = (obj, (matrix_max_approx_1, '3,5,0'))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.52734375
max mem 94.52734375
used mem 0.0
fun output None


In [13]:
t = (maxz, (matrix_max_approx_1,True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.5546875
max mem 94.5234375
used mem -0.03125
fun output {'x1': 2.0, 'x2': 6.0, 'max': 36.0}


In [14]:
def profiling_memory_example(matrix, aux=True):
    """
    Realizar todo el proceso del problema a resolver de optimización con el método Simplex
    """
    constrain(matrix,'1,0,L,4')
    constrain(matrix,'0,2,L,12')
    constrain(matrix,'3,2,L,18')
    obj(matrix,'3,5,0')
    problem_approx_1 = maxz(matrix)
    max_approx_1 = problem_approx_1['max']
    problem_approx_1.pop('max')
    coeff_approx_1 = np.array(list(problem_approx_1.values()))
    
    return max_approx_1, coeff_approx_1

In [15]:
# Todo junto
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
t = (profiling_memory_example, (matrix_max_approx_1,True))
start_mem = memory_usage(max_usage=True)
res = memory_usage(t, max_usage=True, retval=True)
print('start mem', start_mem)
print('max mem', res[0])
print('used mem', res[0]-start_mem)
print('fun output', res[1])

start mem 94.57421875
max mem 89.43359375
used mem -5.140625
fun output (36.0, array([2., 6.]))


In [16]:
# Guardar variables para comprobación
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)
constrain(matrix_max_approx_1,'1,0,L,4')
constrain(matrix_max_approx_1,'0,2,L,12')
constrain(matrix_max_approx_1,'3,2,L,18')
obj(matrix_max_approx_1,'3,5,0')
problem_approx_1 = maxz(matrix_max_approx_1)
max_approx_1 = problem_approx_1['max']
problem_approx_1.pop('max')
coeff_approx_1 = np.array(list(problem_approx_1.values()))

## Comprobación

In [17]:
assert max_obj_1 == approx(max_approx_1), "El valor aproximado es incorrecto"
assert coeff_obj_1 == approx(coeff_approx_1), "El valor de los coeficientes aproximados es incorrecto"

print("El valor objetivo obtenido con scipy es: ", max_obj_1)
print("El valor aproximado obtenido con mex es: ", max_approx_1)
print("Los coeficientes objetivos obtenidos con scipy son: ", coeff_obj_1)
print("Los coeficientes aproximados obtenidos con mex son: ", coeff_approx_1)

El valor objetivo obtenido con scipy es:  35.999999978433735
El valor aproximado obtenido con mex es:  36.0
Los coeficientes objetivos obtenidos con scipy son:  [2. 6.]
Los coeficientes aproximados obtenidos con mex son:  [2. 6.]


# Con `%memit`

In [18]:
%load_ext memory_profiler

In [19]:
%memit

peak memory: 92.77 MiB, increment: -0.30 MiB


In [20]:
%memit -c profiling_memory_example(create_matrix(n_var_approx_1,n_cons_approx_1), True)

peak memory: 98.41 MiB, increment: 5.63 MiB


# Con `%mprun`

In [21]:
from src.profiling.memoria.maxz_memory_profiler import profiling_memory_example

In [22]:
matrix_max_approx_1 = create_matrix(n_var_approx_1,n_cons_approx_1)

In [23]:
%mprun -f profiling_memory_example profiling_memory_example(matrix_max_approx_1)

Filename: /Users/eduardomorenoortiz/Desktop/MaestriaCD/Semestres/Semestre2/optimizacion_avanzada/practicas/practica_2/practica-2-segunda-parte-caroacostatovany/src/profiling/memoria/maxz_memory_profiler.py

Line #    Mem usage    Increment  Occurences   Line Contents
     9     93.5 MiB     93.5 MiB           1   @profile
    10                                         def profiling_memory_example(matrix, aux=True):
    11                                             """
    12                                             Problema a resolver de optimización con el método Simplex
    13                                             """
    14     93.5 MiB      0.0 MiB           1       constrain(matrix, '1,0,L,4')
    15     93.5 MiB      0.0 MiB           1       constrain(matrix, '0,2,L,12')
    16     93.5 MiB      0.0 MiB           1       constrain(matrix, '3,2,L,18')
    17     93.5 MiB      0.0 MiB           1       obj(matrix, '3,5,0')
    18     93.5 MiB      0.0 MiB           1    

# Con `heapy`

In [7]:
%run -i ../src/profiling/memoria/maxz_memory_profile_heapy.py

Partition of a set of 12 objects. Total size = 1400 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1   8      416  30       416  30 types.FrameType
     1      1   8      336  24       752  54 numpy.ndarray
     2      1   8      240  17       992  71 dict (no owner)
     3      2  17      128   9      1120  80 list
     4      3  25       96   7      1216  87 numpy.float64
     5      1   8       80   6      1296  93 builtins.weakref
     6      2  17       64   5      1360  97 int
     7      1   8       40   3      1400 100 _thread.lock


# Para minz

In [8]:
%run -i ../src/profiling/memoria/minz_memory_profile_heapy.py

Partition of a set of 12 objects. Total size = 1320 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1   8      416  32       416  32 types.FrameType
     1      1   8      256  19       672  51 numpy.ndarray
     2      1   8      240  18       912  69 dict (no owner)
     3      2  17      128  10      1040  79 list
     4      3  25       96   7      1136  86 numpy.float64
     5      1   8       80   6      1216  92 builtins.weakref
     6      2  17       64   5      1280  97 int
     7      1   8       40   3      1320 100 _thread.lock


# Para net

In [9]:
%run -i ../src/profiling/memoria/net_memory_profile_heapy.py

Partition of a set of 12 objects. Total size = 2256 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0      1   8     1136  50      1136  50 numpy.ndarray
     1      1   8      416  18      1552  69 types.FrameType
     2      1   8      368  16      1920  85 dict (no owner)
     3      6  50      192   9      2112  94 numpy.float64
     4      1   8       80   4      2192  97 builtins.weakref
     5      2  17       64   3      2256 100 int
